In [2]:
import numpy as np
# from functools import reduce

In [3]:
file_path = '../data/day_13_sample.txt'
# file_path = '../data/day_13.txt'

In [62]:
with open(file_path) as f:
    input_ = f.read().splitlines()

coords, folds = [], []

for line in input_:
    if ',' in line:
        coords.append(list(map(int, line.split(','))))
    elif '=' in line:
        l = line.split('=')
        folds.append((l[0][-1], int(l[1])))

coords = np.array(coords)

sheet = np.zeros(np.max(coords, axis=0)[::-1]+1, dtype=bool)

for (c, r) in coords:
    sheet[r, c] = True

def fold_sheet(a, fold_line):
    axis, idx = fold_line
    if axis == 'x':
        return a[:,:idx] | a[:,:idx:-1]
    elif axis == 'y':
        return a[:idx,:] | a[:idx:-1,:]

answer1 = sum(fold_sheet(sheet, folds[0]).flatten())
# answer2 = reduce(fold_sheet, folds, sheet) # Look at output

print(answer1)

17


In [6]:
with open(file_path, 'r') as file:
    points, folds = [line.splitlines() for line in file.read().split('\n\n')]
           
points = np.array([p.split(',') for p in points]).astype(int)
folds = [x.split()[2].split('=') for x in folds]


xmin = min([int(x[1]) for x in folds if x[0] == 'x'])

ymin = min([int(x[1]) for x in folds if x[0] == 'y'])

grid = np.zeros((ymin, xmin), int)

for x, y in points:
    for fold in folds:
        if fold[0] == 'x':
            x = 0 - abs(x - int(fold[1])) + int(fold[1])
        if fold[0] == 'y':
            y = 0 - abs(y - int(fold[1])) + int(fold[1])
    grid[y][x] = 1

for row in grid:
    print(''.join(['#' if x else '.' for x in row]))

#####
#...#
#...#
#...#
#####
.....
.....


In [52]:
with open(file_path) as f:
    input_ = f.read().splitlines()

coords, folds = [], []

for line in input_:
    if ',' in line:
        coords.append(list(map(int, line.split(','))))
    elif '=' in line:
        l = line.split('=')
        folds.append((l[0][-1], int(l[1])))

coords = np.array(coords)

y_max, x_max = np.max(coords, axis=0)[::-1]+1

sheet = np.zeros((y_max, x_max), dtype=int)

for (c, r) in coords:
    sheet[r, c] = 1

In [53]:
sheet

array([[0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]])

In [16]:
folds  

[('y', 7), ('x', 5)]

In [20]:
sheet = np.delete(sheet, 7, axis=0)

In [21]:
sheets = np.split(sheet, 2, axis=0)

In [25]:
for sheet in sheets:
    print(sheet)

[[0 0 0 1 0 0 1 0 0 1 0]
 [0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 1 0 1]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 1 0 1 1 0]
 [0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 0]]


In [28]:
flipped = np.flipud(sheets[1])
flipped  

array([[1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
combined = sheets[0] + flipped

In [36]:
combined

array([[1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 0, 1, 0, 2, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [37]:
combined = np.delete(combined, 5, axis=1)

In [38]:
combined

array([[1, 0, 1, 1, 0, 1, 0, 0, 1, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 2, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [39]:
split_again = np.split(combined, 2, axis=1)

In [44]:
final_fold = split_again[0]+np.fliplr(split_again[1])
final_fold

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 2, 2, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [45]:
np.count_nonzero(final_fold)

16